- name: Update all packages to their latest version
  ansible.builtin.dnf:
    name: '*'
    state: latest

- name: Install a list of packages
  ansible.builtin.dnf:
    pkg:
      - ansible-core
      - bzip2-devel
      - curl
      - dnf-plugins-core
      - dnf-utils
      - dnsutils
      - fzf
      - gcc
      - git
      - libsqlite3x-devel
      - make
      - openssl-devel
      - origin-clients
      - podman
      - python3-libselinux
      - readline-devel
      - ripgrep
      - the_silver_searcher
      - tmux
      - util-linux-user
      - vim
      - zlib-devel # for pyenv
      - zsh
      - gh

- name: Install pip
  ansible.builtin.dnf:
    name: python3-pip
    state: present

- name: Upgrade pip
  ansible.builtin.pip:
    name: pip
    state: latest

- name: Install KinD
  ansible.builtin.get_url:
    url: https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
    dest: /usr/local/bin/kind
    mode: 0755

