#curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
# - name: Get stable release of kubectl
#   ansible.builtin.shell: >
#     curl -L -s https://dl.k8s.io/release/stable.txt
#   register: kubectl_stable_version
#   when: kubectl_version is not defined

- name: Get stable release of kubectl
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: true
  register: kubectl_stable_version
  when: kubectl_version is not defined

- name: Set kubectl_version
  ansible.builtin.set_fact:
    kubectl_version: "{{ kubectl_stable_version.content }}"
  when: kubectl_version is not defined

- name: Download kubectl for x86_64 Linux
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: /tmp/kubectl
  when: ansible_system == "Linux" and ansible_architecture == "x86_64"

- name: Download kubectl for aarch64 Linux
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/arm64/kubectl"
    dest: /tmp/kubectl
  when: ansible_system == "Linux" and ansible_architecture == "aarch64"

- name: Install kubectl
  ansible.builtin.copy:
    src: /tmp/kubectl
    dest: /usr/local/bin/kubectl
    mode: 0755
    remote_src: true
  become: true
