- name: Add the Docker repository
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/fedora/gpg
    gpgcheck: true
    enabled: true

- name: Install Docker packages
  ansible.builtin.dnf:
    name:
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose
      - docker-compose-plugin

- name: Create docker group
  ansible.builtin.group:
    name: docker

- name: Configure user/groups
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker

- name: Start and enable Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
